### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by KAMAQUEEN** [celebo/hakumod#1]
Let's start with Active Flow, seeing it as a card rather than just a mechanic that encourages aggressive play feels strange. In BB active flow is achieved by playing aggressively and you can only get it once per round. Now as we know, it's not just playing aggressively, but also blocking overheads/escaping throws. So my proposition here is to make active flow a mechanic that activates for the whole fight once you play 5(4?) or more attacks in a single turn or block a massive amount of damage (30?). Now we have a problem with it activating for the whole fight, but as we know, it gets disabled by using an overdrive while it's active and using a break burst disables active flow for the round despite it being activated or not, so i guess you can work with that, even though you need to encourage the use of overdrive as it's kinda feels underwhelming in it's current state, i mean, in the game all of you specials gain something from overdrive, so maybe increase the damage of specials while overdrive is active? To not make this too OP, you can limit the amount of times that you can use overdrive in a single fight by making it unusable after it ends for a couple turns. Now on to break burst, i may be blind, but i don't see it at all, so since we have active flow as an effect instead of a card, you can replace it with break burst, the effect should probably be something like using it on an enemy and negating any damage he does, either by removing strength equal to their damage for one turn from him, or doing something like intangible that applies to an enemy instead (which you'll have to code obviously), again no to make it OP, you will have to make cost 3 energy and just like in BB, use the overdrive, so you can't use break burst for a while after using overdrive and vice versa. Finally, Time Killer, it's very OP, and i don't really have much of an idea to improve it, probably give some debuffs on use and make so it doesn't go through artifact.

Sorry for a big block of text and probably a lot of bad grammar, english isn't my native language, but i hope at least some of my ideas here will be useful.

**Comment by celebo** [comment]
Good evening, thanks for the suggestions. Don't worry about the English, I am not a native English speaker either.

As far as Active Flow is concerned, the reason I made AF the way it is was to make it easier for the players. Not all the Slay The Spires players who pick up the mod are familiar with the intricacies of BB and I felt the character was hard enough to pick up the first time with Special and Gatling already. That's why I only set up on some of it's aspects: The 10% buff and the way AF gives Overdrive, Overdrive gives EA and EA gives AF (or deal double damage if AF is applied).

However, I find the idea you suggested for AF being achieved with aggressive and defensive play interesting. I think it would fit quite well on a relic. So cheers :+1: 

Burst is actually in the game, it's a Token card generated by one of the custom relic "Burst Icon", at the start of battle it shuffles one "Burst" (Power - Cost 0 - Gain 1 Intangible) into the deck.
This way it can only be used once per battle and since you can't control when it appears in your hand, it's not always worth playing. Burst used to be available in the card pool and cost 3. It was later removed to make space for Queen of Rose, a more versatile and fitting card for the character.

Thanks for the suggestions, and I hope you enjoy the mod.
