### ISSUE TITLE
Infinite Tsubaki

### ISSUE THREAD

**Issue by KAMAQUEEN** [celebo/hakumod#2]
If you have Empty Sky active and then do Mugen and it gives you Tsubaki, you can play that Tsubaki an infinite amount of times.
Also a minor thing, some cards like End Gazer say "Gain 6 Blocks" where it should be "Gain 6 Block", it's a little thing, but seeing it again and again kinda get's annoying.

**Comment by celebo** [comment]
The Empty Sky / Tsubaki / Mugen interaction is intentional, it's a reference to a famous combo called the "Tsubacopter" : https://youtu.be/rwuq5ydU_gY?t=23
As this combo relies on 2 rare cards and an uncommon one, one of them being hard to use by most builds, I don't feel it's gamebreaking enough to warrant a nerf.
Thanks for reporting the typo, new patch will be released later this week.
